// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLastApi.Migrations;

#nullable disable

namespace MyLastApi.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230808022203_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyLastApi.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "08995228407",
                            DataNasc = new DateTime(1992, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "60671150006",
                            DataNasc = new DateTime(1963, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fatima"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "47633984074",
                            DataNasc = new DateTime(1980, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Orlando"
                        });
                });

            modelBuilder.Entity("MyLastApi.Models.Conta", b =>
                {
                    b.Property<int>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConta"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimiteDiario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumConta")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdConta");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            IdConta = 1,
                            Agencia = "0123",
                            Ativa = true,
                            Bloqueada = false,
                            LimiteDiario = 0m,
                            NumConta = 1,
                            Saldo = 0m
                        },
                        new
                        {
                            IdConta = 2,
                            Agencia = "0123",
                            Ativa = true,
                            Bloqueada = false,
                            LimiteDiario = 0m,
                            NumConta = 2,
                            Saldo = 0m
                        },
                        new
                        {
                            IdConta = 3,
                            Agencia = "0123",
                            Ativa = true,
                            Bloqueada = false,
                            LimiteDiario = 0m,
                            NumConta = 3,
                            Saldo = 0m
                        });
                });

            modelBuilder.Entity("MyLastApi.Models.Operacao", b =>
                {
                    b.Property<int>("IdOperacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOperacao"));

                    b.Property<int?>("ContaIdConta")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Valor")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOperacao");

                    b.HasIndex("ContaIdConta");

                    b.ToTable("Operacoes");

                    b.HasData(
                        new
                        {
                            IdOperacao = 1,
                            DataOperacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacao = "Depósito",
                            Valor = 8798.13m
                        },
                        new
                        {
                            IdOperacao = 2,
                            DataOperacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoOperacao = "Saque",
                            Valor = 452.17m
                        });
                });

            modelBuilder.Entity("MyLastApi.Models.Conta", b =>
                {
                    b.HasOne("MyLastApi.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyLastApi.Models.Operacao", b =>
                {
                    b.HasOne("MyLastApi.Models.Conta", "Conta")
                        .WithMany("Operacoes")
                        .HasForeignKey("ContaIdConta");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("MyLastApi.Models.Conta", b =>
                {
                    b.Navigation("Operacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
